// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/deps.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/genexterns.js', ['nclosure.genexterns'], ['goog.array', 'nclosure']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/goog.js', ['nclosure'], ['goog.Timer', 'goog.string', 'nclosure_nclosurebase', 'nclosure_opts', 'nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/nclosurebase.js', ['nclosure_nclosurebase'], ['nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/node.externs.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/node.static.externs.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/lib/settingsloader.js', ['nclosure_opts', 'nclosure_settingsLoader'], []);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/checkAllSampleTestsPassing.js', ['nclosure.tests.checkAllSampleTestsPassing'], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit', 'nclosure.tests']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/checkAllSamplesAreRunningTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/closureUtilsTests.js', [], ['goog.testing.jsunit', 'nclosure.NodeTestsRunner']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/compileAndCheckFilesTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/compilerCommandLineArgsTests.js', [], ['goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/deps.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/docFrameworkTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/googNodeTestFrameworkTests.js', [], ['goog.array', 'goog.testing.jsunit', 'nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/runClosureLibraryJSUnitsManual.js', [], ['goog.testing.jsunit', 'nclosure.tests']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/settingsLoaderTests.js', [], ['goog.testing.jsunit', 'nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/nclosure/tests/utils.js', ['nclosure.tests'], ['goog.array']);
