// This file was autogenerated by /home/ubuntu/Dev/projects/node-goog/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/checkAllSampleTestsPassing.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit', 'nclosure.tests']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/checkAllSamplesAreRunningTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/compileAndCheckFilesTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/compilerCommandLineArgsTests.js', [], ['goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/deps.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/docFrameworkTests.js', [], ['goog.array', 'goog.testing.AsyncTestCase', 'goog.testing.jsunit']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/googNodeTestFrameworkTests.js', [], ['goog.array', 'goog.testing.jsunit', 'nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/runClosureLibraryJSUnitsManual.js', [], ['goog.testing.jsunit', 'nclosure.tests']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/settingsLoaderTests.js', [], ['goog.testing.jsunit', 'nclosure_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/tests/utils.js', ['nclosure.tests'], ['goog.array', 'nclosure']);
