// This file was autogenerated by /home/ubuntu/Dev/projects/nclosure/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../examples/tutorial/deps.js', [], []);
goog.addDependency('../../../../examples/tutorial/docs/javascript/all.js', [], []);
goog.addDependency('../../../../examples/tutorial/docs/javascript/html5.js', [], []);
goog.addDependency('../../../../examples/tutorial/docs/javascript/prettify.js', [], []);
goog.addDependency('../../../../examples/tutorial/fileinfo.js', ['demo.fileinfo'], ['goog.debug']);
goog.addDependency('../../../../examples/tutorial/listfiles.js', ['demo.listfiles'], ['goog.array']);
goog.addDependency('../../../../examples/tutorial/listfiles2.js', ['demo.listfiles2'], ['demo.fileinfo', 'goog.array']);
goog.addDependency('../../../../examples/tutorial/listfiles3.js', ['demo.listfiles3'], ['demo.fileinfo', 'goog.array']);
goog.addDependency('../../../../examples/tutorial/tests/allTests.js', [], ['demo.fileinfo', 'goog.testing.jsunit']);
goog.addDependency('../../../../examples/tutorial/tests/testingSuite.js', [], []);
