// This file was autogenerated by ../picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/external_lib/Utils.js', ['node.goog.external.Utils'], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/external_lib/Utils.min.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/external_lib/deps.js', [], []);
