// This file was autogenerated by /home/ubuntu/Dev/projects/node-goog/third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/genexterns.js', ['node.goog.genexterns'], ['goog.array', 'node.goog']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/goog.js', ['node.goog'], ['goog.Timer', 'goog.string', 'node_goog_googbase', 'node_goog_opts', 'node_goog_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/googbase.js', ['node_goog_googbase'], ['node_goog_settingsLoader']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/node.externs.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/node.static.externs.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/lib/settingsloader.js', ['node_goog_opts', 'node_goog_settingsLoader'], []);
