// This file was autogenerated by ../picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/cat.js', ['node.goog.examples.animals.Cat'], ['node.goog.examples.animals.CatLike', 'node.goog.examples.animals.IAnimal']);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/catlike.js', ['node.goog.examples.animals.CatLike'], ['node.goog.examples.animals.IAnimal']);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/deps.js', [], []);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/dog.js', ['node.goog.examples.animals.Dog'], ['node.goog.examples.animals.IAnimal']);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/example.js', ['node.goog.examples.animals.Example'], ['goog.array', 'node.goog.examples.animals.Cat', 'node.goog.examples.animals.Dog', 'node.goog.examples.animals.IAnimal', 'node.goog.examples.animals.Monkey', 'node.goog.examples.animals.Tiger']);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/example.min.js', [], []);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/ianimal.js', ['node.goog.examples.animals.IAnimal'], []);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/monkey.js', ['node.goog.examples.animals.Monkey'], ['node.goog.examples.animals.IAnimal']);
goog.addDependency('/home/guidot/dev/node-goog/examples/animals/tiger.js', ['node.goog.examples.animals.Tiger'], ['node.goog.examples.animals.CatLike', 'node.goog.examples.animals.IAnimal']);
