// This file was autogenerated by ../lib/picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/gatapia/dev/node-goog/examples/simple/deps.js', [], []);
goog.addDependency('/home/gatapia/dev/node-goog/examples/simple/example.js', ['node.goog.examples.simple.Example'], ['goog.async.Delay', 'goog.structs.Trie', 'node.goog.external.Utils']);
goog.addDependency('/home/gatapia/dev/node-goog/examples/simple/example.min.js', [], []);
