// This file was autogenerated by /home/ubuntu/Dev/projects/node-goog/bin/../../../lib/picnet-closure-repo/lib/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/simple/deps.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/simple/example.js', ['node.goog.examples.simple.Example'], ['goog.async.Delay', 'goog.structs.Trie', 'node.goog.external.Utils']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/simple/example.min.js', [], []);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/simple/tests/async/asyncTests.js', ['node.goog.examples.simple.tests.asyncTests'], ['goog.testing.AsyncTestCase', 'goog.testing.jsunit', 'node.goog.examples.simple.Example']);
goog.addDependency('/home/ubuntu/Dev/projects/node-goog/examples/simple/tests/syncTests.js', ['node.goog.examples.simple.tests.syncTests'], ['goog.testing.jsunit', 'node.goog.examples.simple.Example']);
